/*
===============================================================================
Analytical Exploration & Insights
===============================================================================
Script Purpose:
    This script contains analytical SQL queries designed to generate insights 
    from the curated 'Gold' layer of the Data Warehouse. It supports business 
    intelligence and reporting by quantifying performance, ranking entities, 
    and tracking changes over time.

Key Analytical Areas:

    1. Magnitude Analysis
        - Quantifies data and aggregates results across key dimensions.
        - Helps understand data distribution across categories such as region, product, or customer.
        - SQL Functions Used:
            - Aggregate Functions: SUM(), COUNT(), AVG()
            - GROUP BY, ORDER BY

    2. Ranking Analysis
        - Ranks items (e.g., top products, best customers) based on key metrics.
        - Identifies high and low performers for strategic decisions.
        - SQL Functions Used:
            - Window Functions: RANK(), DENSE_RANK(), ROW_NUMBER(), TOP
            - GROUP BY, ORDER BY

    3. Change Over Time Analysis
        - Tracks growth, decline, and trends in metrics over time.
        - Enables time-series and seasonality analysis for forecasting.
        - SQL Functions Used:
            - Date Functions: DATEPART(), DATETRUNC(), FORMAT()
            - Aggregate Functions: SUM(), COUNT(), AVG()

===============================================================================
*/


use DataWarehouseAnalytics;

-- ===============================================================================
-- Magnitude Analysis
-- ===============================================================================

--Find total customers by countries
select
	country,
	count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;


--Find total customers by gender
select
	gender,
	count(customer_key) as total_customers
from gold.dim_customers
group by gender
order by total_customers desc;


--Find total products by category
select
	category,
	count(product_key) as total_product
from gold.dim_products
group by category
order by total_product desc;

--What is the average costs in each category?
select
	category,
	avg(cost) as avg_cost
from gold.dim_products
group by category
order by avg_cost desc;

--What is the total revenue generated for each category?
select
	p.category,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.category
order by total_revenue desc;

--Find total revenue is generated by each customer
select
	c.customer_key,
	c.first_name,
	c.last_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.customer_key,c.first_name,c.last_name
order by first_name,total_revenue desc;

--What is the distribution of sold items across countries?
select
	c.country,
	sum(f.quantity) as total_sold_items
from gold.fact_sales f
left join gold.dim_customers c
on f.customer_key = c.customer_key
group by c.country
order by total_sold_items desc;

-- ===============================================================================
-- Ranking Analysis
-- ===============================================================================

-- Which 5 products generate the highest revenue
select top 5
	p.product_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.product_name
order by total_revenue desc;

-- Using Window Quary
select * 
from(
	select
		p.product_name,
		sum(f.sales_amount) as total_revenue,
		ROW_NUMBER() over (order by sum(f.sales_amount) desc) as rank_products
	from gold.fact_sales f
	left join gold.dim_products p
	on f.product_key = p.product_key
	group by p.product_name) t
where rank_products <= 5;

-- what are the 5 worst-performing products in the terms of sales
select top 5
	p.product_name,
	sum(f.sales_amount) as total_revenue
from gold.fact_sales f
left join gold.dim_products p
on f.product_key = p.product_key
group by p.product_name
order by total_revenue asc;

-- Find the top 10 customers who have generated the highest revenue
select top 10
    c.customer_key,
    c.first_name,
    c.last_name,
    sum(f.sales_amount) as total_revenue
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
    on c.customer_key = f.customer_key
group by 
    c.customer_key,
    c.first_name,
    c.last_name
order by total_revenue desc;

-- The 3 customers with the fewest orders placed
select top 3
    c.customer_key,
    c.first_name,
    c.last_name,
    count(distinct order_number) as total_orders
from gold.fact_sales f
LEFT JOIN gold.dim_customers c
    on c.customer_key = f.customer_key
group by 
    c.customer_key,
    c.first_name,
    c.last_name
order by total_orders asc;

-- ===============================================================================
-- Change Over Time Analysis
-- ===============================================================================

-- Analyse sales performance over time
/* "What are the monthly sales performance metrics — including total sales, number of unique customers, 
    and total quantity sold — for each year based on the gold.fact_sales table?" */

select
    year(order_date) as order_year,
    month(order_date) as order_month,
    sum(sales_amount) as total_sales,
    count(distinct customer_key) as total_customers,
    sum(quantity) as total_quantity
from gold.fact_sales
where order_date IS NOT NULL
group by year(order_date), month(order_date)
order by year(order_date), month(order_date);

-- DATETRUNC()
select
    datetrunc(month, order_date) as order_date,
    sum(sales_amount) as total_sales,
    count(distinct customer_key) as total_customers,
    sum(quantity) as total_quantity
from gold.fact_sales
where order_date IS NOT NULL
group by datetrunc(month, order_date)
order by datetrunc(month, order_date);

